version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build --stacktrace -Dorg.gradle.java.home=/usr/lib/jvm/java-8-openjdk-amd64
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew shadowJar --stacktrace -Dorg.gradle.java.home=/usr/lib/jvm/java-8-openjdk-amd64
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release
