version: 2
jobs:
  build:
    machine:
      enabled: true
      java:
        version: 'oraclejdk8'
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build
  release:
    machine:
      enabled: true
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew shadowJar --stacktrace
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release
